from pathlib import Path
from datetime import datetime, timezone
import json
import html

def generate_reports(domain, results, output_dir, logger=None):
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")

    txt_path = output_dir / f"{domain}_{timestamp}.txt"
    json_path = output_dir / f"{domain}_{timestamp}.summary.json"
    html_path = output_dir / f"{domain}_{timestamp}.html"

    _generate_txt(domain, results, txt_path)
    _generate_json(results, json_path)
    _generate_html(domain, results, html_path, timestamp)

    if logger:
        logger.info(f"Reports generated at {output_dir}")


def _generate_txt(domain, results, path):
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"Recon Report for {domain}\n")
        f.write("=" * 40 + "\n\n")

        # Passive Recon
        f.write("[PASSIVE RECON]\n")

        passive = results.get("passive", {})
        for module, data in passive.items():
            f.write(f"\n{module.upper()}:\n")
            if not data:
                f.write("  No data found\n")
            else:
                f.write(str(data) + "\n")

        # Active Recon
        f.write("\n[ACTIVE RECON]\n")

        active = results.get("active", {})

        # Port Scan
        portscan = active.get("portscan")
        if portscan:
            f.write("\nOpen Ports:\n")
            for port in portscan.get("open_ports", []):
                f.write(f"  - {port}\n")

        # Banner Grabbing
        banners = active.get("banners")
        if banners:
            f.write("\nService Banners:\n")
            for port, banner in banners.items():
                f.write(f"  Port {port}: {banner}\n")


def _generate_json(results, path):
    import json
    with open(path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)

def _generate_html(domain, results, path, timestamp):
    def esc(text):
        return html.escape(str(text))

    passive = results.get("passive", {})
    active = results.get("active", {})

    with open(path, "w", encoding="utf-8") as f:
        f.write(f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Recon Report - {esc(domain)}</title>
<style>
body {{
    font-family: Arial, sans-serif;
    background-color: #0f172a;
    color: #e5e7eb;
    padding: 20px;
}}
h1, h2 {{
    color: #38bdf8;
}}
.section {{
    margin-bottom: 30px;
}}
.box {{
    background: #020617;
    padding: 15px;
    border-radius: 8px;
}}
pre {{
    white-space: pre-wrap;
    word-wrap: break-word;
}}
ul {{
    list-style: none;
    padding-left: 0;
}}
li {{
    padding: 4px 0;
}}
.footer {{
    margin-top: 40px;
    font-size: 0.9em;
    color: #94a3b8;
}}
</style>
</head>
<body>

<h1>Recon Report</h1>
<p><strong>Target:</strong> {esc(domain)}</p>
<p><strong>Generated (UTC):</strong> {esc(timestamp)}</p>

<div class="section">
<h2>Passive Recon</h2>
""")

        for module, data in passive.items():
            f.write(f"""
<div class="box">
<h3>{esc(module.upper())}</h3>
<pre>{esc(json.dumps(data, default=str))}</pre>
</div>
""")

        f.write("""
</div>
<div class="section">
<h2>Active Recon</h2>
""")

        portscan = active.get("portscan")
        if portscan:
            f.write("""
<div class="box">
<h3>Open Ports</h3>
<ul>
""")
            for port in portscan.get("open_ports", []):
                f.write(f"<li>Port {esc(port)}</li>")
            f.write("</ul></div>")

        banners = active.get("banners")
        if banners:
            f.write("""
<div class="box">
<h3>Service Banners</h3>
<pre>
""")
            for port, banner in banners.items():
                f.write(f"Port {esc(port)}: {esc(banner)}\n")
            f.write("</pre></div>")

        f.write(f"""
</div>

<div class="footer">
Generated by Custom Recon Tool
</div>

</body>
</html>
""")